# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: time-service
replicaCount: 2

container:
  port: 4000
image:
  repository: time-service
  name: eilonash92/time-service:latest
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: LoadBalancer
  port: 4000
